api-version: 1.13
main: "no.openshell.oddstr13.minecartmeter.MinecartMeter"
name: "MinecartMeter"
version: "${project.version}"
description: "See how far the minecart trip brought you, and the time it took."
author: "Oddstr13"
website: "https://github.com/oddstr13/MinecartMeter"
commands:
  minecartmeter:
    Description: "Do MinecartMeter stuff"
    Usage: "/minecartmeter"
