main: "no.openshell.oddstr13.minecartmeter.MinecartMeter"
name: "MinecartMeter"
version: "0.0.1"
description: "Show distance and time traveled by minecart when exiting the minecart."
author: "Oddstr13"
website: "https://github.com/oddstr13/MinecartMeter"
commands:
  minecartmeter:
    Description: 'Do MinecartMeter stuff'
    Usage: '/minecartmeter'

